name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/CONTRIBUTING.md'
      - '**/CONTRIBUTORS.txt'
      - '**/LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/CONTRIBUTING.md'
      - '**/CONTRIBUTORS.txt'
      - '**/LICENSE'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 15, 16, 17 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'corretto'
    - name: Compile with Maven
      run: mvn -T 1C clean generate-sources compile --file pom.xml
      
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 15, 16, 17 ]
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'corretto'
    - name: Test with Maven
      run: mvn -T 1C test-compile test --file pom.xml
  
  sonarcloud:
    environment: sonarcloud
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'corretto'
    - name: SonarCloud Scan
      run: mvn clean test jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=amazon-sns-java-messaging-lib -Dsonar.organization=mvallim -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
